// mock data
module.exports = {
  xOAuth2: 
  "dXNlcj1tYWlsc3luYzIwMThAZ21haWwuY29tAWF1dGg9QmVhcmVyIHlhMjkuR2x5MEJmWGEwaDh4c3ctazNxckRoeldaWjE0akFJWXFUenJTZjVYdUJiY0FZMzIzU1hHZW5EY1dsMldLQnFIMEliZlZKMGVacUJCMElYOVRoRGJyc2tveWpHTDhwVDR1VDFHSVprWkFweVFPdk9ndWZVYWkyeTd1LV9xbTBBAQE="
};
